import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from './ui/footer'
import Navbar from './ui/navbar'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
      {/* Navbar */}
      <nav className="bg-white shadow sticky top-0 z-50">
        <Navbar />
      </nav>
        {children}
        <footer className="py-6 bg-gray-800 text-white">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
